spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/to-do-list/demo
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug

#  org.hibernate.type: trace